Question no 1

In [ ]:
#takes the type and the value
def convertLen(x,type):
  if (type=="meters"):
    result=x*3.28
  elif(type=="feet"):
    result=x/3.28
  return result

#takes weigth and the type accodingly
def convertWeght(x,type):
  if (type=="kilograms"):
    result=x*2.20
  elif(type=="pounds"):
    result=x/2.20
  return result

#takes volume and the type
def convertVol(x,type):
  if (type=="liters"):
    result=x*3.78
  elif(type=="gallons"):
    result=x/3.78
  return result

In [ ]:
conversion=input("Enter the type of conversion: length, weight, volume")
a=input("Enter the value you want to covert: ")
try:
    a=int(a)
except:
    print("Sorry invalid input")
type=input("Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallons")
match conversion:
  case "length":
    print(convertLen(a,type))
  case "weight":
    print(convertWeght(a,type))
  case "volume":
    print(convertVol(a,type))

Enter the type of conversion: length, weight, volumelength
Enter the value you want to covert: 10
Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallonsfeet
3.048780487804878


Question no 2

In [ ]:
def sum(x):
  # Takes a list as input and returns the sum of its elements
  result = 0
  for num in x:
    result += num
  return result

def average(x):
  # Takes a list as input and returns the average of its elements
  result = 0
  for num in x:
    result += num
  result = result / len(x)
  return result

def maximum(x):
  # Takes a list as input and returns the maximum value from the list
  return max(x)

def minimum(x):
  # Takes a list as input and returns the minimum value from the list
  return min(x)

In [ ]:
a=input("Enter a list that is seperated by spaces")
try:
  list=[int(x) for x in a if x.isnumeric()]
except:
  print("Please enter valid numbers")
operation=input("Enter the operation: sum, average,maximum,minimum")
match operation:
  case "sum":
    print(sum(list))
  case "average":
    print(average(list))
  case "maximum":
    print(maximum(list))
  case "minimum":
    print(minimum(list))

Enter a list that is seperated by spaces2 3 4
Enter the operation: sum, average,maximum,minimumsum
9


Question no 3

In [ ]:
def extractList(lists):
  newList=[x for index,x in enumerate(lists) if index%2==0]
  return newList

print(extractList([1,2,3,4,5,6,7,8]))

[1, 3, 5, 7]


Question no 4

In [ ]:
def getSublist(lists,start,end):
  newList=lists[start:end+1]
  return newList

print(getSublist([1,2,3,4,5,6,7,8],2,5))

[3, 4, 5, 6]


Question no 5

In [ ]:
def reverseList(lists):
  newList=lists[::-1]
  return newList

print(reverseList([1,2,3,4,5,6,7,8]))

[8, 7, 6, 5, 4, 3, 2, 1]


Question no 6

In [ ]:
def removeFirstLast(lists):
  newList=lists[1:-1]
  return newList

print(removeFirstLast([1,2,3,4,5,6,7,8]))

[2, 3, 4, 5, 6, 7]


Question no 7

In [ ]:
def getFirstN(lists,n):
  newList=lists[:n]
  return newList
print(getFirstN([1,2,3,4,5,6,7,8],3))

[1, 2, 3]


Question no 8

In [ ]:
def getLastN(lists,n):
  newList=lists[len(lists)-n:]
  return newList

print(getLastN([1,2,3,4,5],2))


[4, 5]


Question no 9

In [ ]:
def reverseSkip(lists):
  newList=lists[::-1]
  newList=newList[1::2]
  return newList

print(reverseSkip([1,2,3,4,5,6]))

[5, 3, 1]


Question no 10

In [ ]:
def flatten(lst):
  new_list=[]
  for x in lst:
    for y in x:
      new_list.append(y)
  return new_list

print(flatten([[1,2,3],[4,5,6]]))

[1, 2, 3, 4, 5, 6]


Question no 11

In [ ]:
def accessedNestedElement(lists,indices):
  for index in indices:
    lists=lists[index]
  return lists

print(accessedNestedElement([[1,2,3],[4,5,6],[7,8,9]],[1,2]))

6


Question no 12

In [ ]:
from collections.abc import Iterable

def sum_nested(lst):
  total = 0
  for x in lst:
    if isinstance(x, Iterable) and not isinstance(x, str):
      for y in x:
        if isinstance(y, Iterable) and not isinstance(y, str):
          for z in y:
            total += z
        else:
          total += y
    else:
      total += x
  return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))


21


Question no 13

In [ ]:
def removeElement(lst,elem):
  for x in lst:
    for y in x:
      if(y==elem):
        x.remove(y)
  return lst

print(removeElement([[1, 2], [3, 2], [4, 5]],2))

[[1], [3], [4, 5]]


Question no 14

In [ ]:
def find_max(lst):
  max_val = 0
  for x in lst:
    if type(x) == list:
      for y in x:
        if type(y) == list:
          for z in y:
            if z > max_val:
              max_val = z
        else:
          if y > max_val:
            max_val = y
    else:
      if x > max_val:
        max_val = x
  return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


Question no 15

In [1]:
def countOccurences(lists,elem):
  count=0
  for x in lists:
    for y in x:
      if(y==elem):
        count+=1;
  return count
print(countOccurences([[1,2],[3,2],[4,2]],2))

3


Question no 16

In [5]:
def deepFlatten(lists):
  newList=[]
  for x in lists:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            newList.append(z)
        else:
            newList.append(y)
    else:
      newList.append(x)
  return newList

print(deepFlatten([[1, 2], [3, [4, 5]], 6]))

[1, 2, 3, 4, 5, 6]


Question no 17

In [17]:
def average_nested(lst):
  avg=0
  sum=0
  length=0
  for x in lst:
    for y in x:
      sum+=y
      length+=1
  avg=sum/length
  return avg

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


Question no *18*

In [16]:
import numpy as np
emptyArray=np.empty(4)
oneArray=np.ones((4,4))
fullArray=np.full((2,2),5)
zeroLikeArray=np.zeros_like(oneArray)
oneLikeArray=np.ones_like(oneArray)
listsArray=np.array([11,22,33,44])
print(emptyArray)
print(oneArray)
print(fullArray)
print(zeroLikeArray)
print(oneLikeArray)
print(listsArray)

[5.43e-323 1.09e-322 1.63e-322 2.17e-322]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5]
 [5 5]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[11 22 33 44]


Question no 19

In [19]:
rangeArray=np.arange(10,49)
matrix=np.arange(0,9).reshape((3,3))
eyeMatrix=np.eye(3)
rand=np.random.random((3,3))
mean=rand.mean()
rand1=np.random.random((10,10))
max=rand1.max()
min=rand1.min()
zeroarr=np.zeros((10,10))
zeroarr[6]=1
arr=[1,2,0,0,4,0]
reverseArray=arr[::-1]
arrborder=np.zeros((3,3))
arrborder[0,:]=1
arrborder[:,0]=1
arrborder[:,-1]=1
arrborder[-1,:]=1
checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(rangeArray)
print(matrix)
print(eyeMatrix)
print(rand)
print(mean)
print(rand1)
print(max)
print(min)
print(zeroarr)
print(reverseArray)
print(arrborder)
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.52877582 0.02690855 0.39147436]
 [0.8963429  0.64671456 0.065289  ]
 [0.16574867 0.00628229 0.34114099]]
0.340964125532502
[[0.83048436 0.48928426 0.40036917 0.68914187 0.34301469 0.49047088
  0.96467798 0.36350254 0.63932907 0.37770339]
 [0.80290977 0.68916198 0.82804211 0.91324908 0.6650209  0.56730755
  0.65527534 0.80898298 0.06264263 0.01654576]
 [0.27426967 0.99330331 0.1486921  0.17549058 0.74299491 0.82344214
  0.19634337 0.46091856 0.32145239 0.63863344]
 [0.06729067 0.96447343 0.67869131 0.78037584 0.14289092 0.21417074
  0.02702899 0.40126375 0.55511972 0.5647105 ]
 [0.24347374 0.44435734 0.31042719 0.21867109 0.02327832 0.16631966
  0.57083561 0.86171381 0.3048299  0.13319998]
 [0.37126734 0.8150171  0.87993927 0.01572821 0.91034987 0.28957984
  0.37583068 0.77351941 0.68468539 0.70937627

Question no 20

In [20]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum=np.add(x,y)
sub=np.subtract(x,y)
multiply=np.multiply(x,y)
square=np.square(x)
vdotw=np.dot(v,w)
xdotv=np.dot(x,v)
xdoty=np.dot(x,y)
rowconcat=np.concatenate((x,y),axis=0)
columnconcat=np.concatenate((x,y),axis=1)
print(sum)
print(sub)
print(multiply)
print(square)
print(vdotw)
print(xdotv)
print(xdoty)
print(rowconcat)
print(columnconcat)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]


Question no 21

In [27]:
firstArray = np.array([[3,4],[7,8]])
secondArray = np.array([[1,2],[2,1]])
ainverse=np.linalg.inv(firstArray)
eye=firstArray@ainverse
AB=np.matmul(firstArray,secondArray)
BA=np.matmul(secondArray,firstArray)
At=np.transpose(firstArray)
Bt=np.transpose(secondArray)
ABt=np.transpose(AB)
BtAt=np.matmul(Bt,At)
print(eye)
print(AB)
print(BA)
print(ABt)
print(BtAt)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[11 10]
 [23 22]]
[[17 20]
 [13 16]]
[[11 23]
 [10 22]]
[[11 23]
 [10 22]]
